using System.Reflection;
using Ami.BroAudio.Data;
using UnityEngine;

namespace Ami.BroAudio.Tests
{
    /// <summary>
    /// Builds audio entities in code so tests never depend on authored assets.
    /// Uses <see cref="AudioEntity.CreateNewInstance"/> — a raw CreateInstance leaves MasterVolume and Pitch at 0.
    /// </summary>
    public static class TestAudioLibrary
    {
        private const BindingFlags PrivateInstance = BindingFlags.Instance | BindingFlags.NonPublic;
        public const int SampleRate = 44100;

        /// <summary>Concrete audio types, i.e. All without the composite flag.</summary>
        public static readonly BroAudioType[] ConcreteAudioTypes =
        {
            BroAudioType.Music, BroAudioType.UI, BroAudioType.Ambience, BroAudioType.SFX, BroAudioType.VoiceOver,
        };

        /// <summary>A procedurally generated sine clip of an exactly known length.</summary>
        public static AudioClip CreateClip(float seconds = 1f, string name = "TestClip")
        {
            int sampleCount = Mathf.Max(1, Mathf.RoundToInt(seconds * SampleRate));
            var clip = AudioClip.Create(name, sampleCount, 1, SampleRate, false);
            float[] data = new float[sampleCount];
            for (int i = 0; i < sampleCount; i++)
            {
                data[i] = Mathf.Sin(2f * Mathf.PI * 440f * i / SampleRate) * 0.25f;
            }
            clip.SetData(data, 0);
            return clip;
        }

        public static BroAudioClip CreateBroClip(AudioClip clip)
        {
            var broClip = new BroAudioClip();
            SetPrivateField(broClip, BroAudioClip.NameOf.AudioClip, clip);
            return broClip;
        }

        /// <summary>Creates a playable entity. Passing no clips generates one 1-second clip.</summary>
        public static AudioEntity CreateEntity(string name, BroAudioType audioType, params AudioClip[] clips)
        {
            if (clips == null || clips.Length == 0)
            {
                clips = new[] { CreateClip(name: name + "Clip") };
            }

            var entity = AudioEntity.CreateNewInstance(null, name, audioType);
            entity.Clips = new BroAudioClip[clips.Length];
            for (int i = 0; i < clips.Length; i++)
            {
                entity.Clips[i] = CreateBroClip(clips[i]);
            }
            return entity;
        }

        /// <summary>
        /// Creates a playable entity exactly like <see cref="CreateEntity"/>, but with the per-clip
        /// <see cref="BroAudioClip.Volume"/> and entity <see cref="AudioEntity.MasterVolume"/> authored away
        /// from their shared default of 1f (AudioConstant.FullVolume). Neither factor can be moved off 1
        /// by any other factory here, which leaves AudioPlayer.Playback.cs's `_clip.Volume *
        /// _pref.Entity.GetMasterVolume()` product (AudioPlayer.Playback.cs:276, SetupClipVolume) unable to
        /// ever read as anything but 1 * 1 in the suite - this is the smallest addition that fixes that.
        /// <para>
        /// <see cref="BroAudioClip.Volume"/> is a plain public field, so it's written directly; MasterVolume
        /// is `private set` like most of <see cref="AudioEntity"/>, so it goes through <see cref="SetPrivateField"/>
        /// against the auto-property's backing field, the same way every other authored AudioEntity field in
        /// this suite (RandomFlags, VolumeRandomRange, Loop, ...) is written.
        /// </para>
        /// </summary>
        public static AudioEntity CreateEntityWithVolume(string name, BroAudioType audioType, float clipVolume, float masterVolume, params AudioClip[] clips)
        {
            AudioEntity entity = CreateEntity(name, audioType, clips);
            foreach (BroAudioClip clip in entity.Clips)
            {
                clip.Volume = clipVolume;
            }
            SetPrivateField(entity, nameof(AudioEntity.MasterVolume), masterVolume);
            return entity;
        }

#if PACKAGE_ADDRESSABLES
        /// <summary>
        /// GUIDs of the suite's own addressable fixtures — <c>Assets/Tests/Fixtures/AddressableTone{A,B}.wav</c>,
        /// addressed as <c>BroAudioTest/ToneA</c> and <c>BroAudioTest/ToneB</c> in the Default Local Group.
        /// <para>
        /// These are half-second sine tones generated by <c>Tools > BroAudio > Tests > Regenerate Addressable
        /// Fixtures</c> and committed, rather than built at runtime like <see cref="CreateClip"/>: an
        /// AssetReference resolves through the AssetDatabase, so an addressable clip has to be a real asset.
        /// They deliberately live outside <c>Assets/BroAudio/Samples</c>, which ships as <c>Samples~</c> and is
        /// therefore invisible to Unity on CI.
        /// </para>
        /// </summary>
        public static readonly string[] AddressableClipGuids =
        {
            "3466b5a562524ab2aaf09db0429c665f",
            "c3e9b7bf8cf5472d9cffbdafae49b73d",
        };

        /// <summary>
        /// Builds a clip backed by an addressable asset rather than a direct reference, so
        /// <c>IsAddressablesAvailable()</c> reports true and the load paths engage.
        /// </summary>
        public static BroAudioClip CreateAddressableBroClip(string guid)
        {
            var broClip = new BroAudioClip();
            FieldInfo field = typeof(BroAudioClip).GetField(BroAudioClip.NameOf.AudioClipAssetReference, PrivateInstance);
            field.SetValue(broClip, new UnityEngine.AddressableAssets.AssetReferenceT<AudioClip>(guid));
            return broClip;
        }

        /// <summary>Creates an entity whose clips all resolve through Addressables.</summary>
        public static AudioEntity CreateAddressableEntity(string name, BroAudioType audioType, params string[] guids)
        {
            if (guids == null || guids.Length == 0)
            {
                guids = new[] { AddressableClipGuids[0] };
            }

            var entity = AudioEntity.CreateNewInstance(null, name, audioType);
            entity.UseAddressables = true;
            entity.Clips = new BroAudioClip[guids.Length];
            for (int i = 0; i < guids.Length; i++)
            {
                entity.Clips[i] = CreateAddressableBroClip(guids[i]);
            }
            return entity;
        }
#endif

        /// <summary>
        /// Reads a private field or an auto-property backing field, walking the type hierarchy.
        /// The read counterpart of <see cref="SetPrivateField"/>, for state a type exposes no getter for
        /// (e.g. <c>SoundVolume.Setting</c>'s current volume).
        /// </summary>
        public static T GetPrivateField<T>(object target, string fieldName)
        {
            return (T)GetFieldOrThrow(target, fieldName).GetValue(target);
        }

        /// <summary>
        /// Writes a private field or an auto-property backing field, walking the type hierarchy.
        /// Needed because most of <see cref="AudioEntity"/> is `private set`.
        /// </summary>
        public static void SetPrivateField(object target, string fieldName, object value)
        {
            GetFieldOrThrow(target, fieldName).SetValue(target, value);
        }

        private static FieldInfo GetFieldOrThrow(object target, string fieldName)
        {
            System.Type type = target.GetType();
            while (type != null)
            {
                FieldInfo field = type.GetField(fieldName, PrivateInstance)
                                  ?? type.GetField($"<{fieldName}>k__BackingField", PrivateInstance);
                if (field != null)
                {
                    return field;
                }
                type = type.BaseType;
            }
            throw new System.MissingFieldException(target.GetType().Name, fieldName);
        }
    }
}